### ISSUE TITLE
How to specify shema name when migration?

### ISSUE THREAD

**Issue by yongwoon** [rust-db/refinery#205] opened 2022-01-05 13:48 UTC
I trying to migration.

sucess to migration ref the #105. 
but I couldn't specify schema.

How can I set schema when migration?

```
mod embedded {
    use refinery::embed_migrations;
    embed_migrations!("./migrations");
}

let _report = embedded::migrations::runner()
                          .run_async(client)
                           .await.unwrap();
```

**Comment by jxs** [comment] 2022-01-05 15:53
Hi, thanks for your interest! This seems a duplicate of https://github.com/rust-db/refinery/issues/123 right?

**Comment by TobiasDeBruijn** [comment] 2022-01-05 20:35
I'm interested in implementing this partially, specifically a custom name for the migration table, if that is alright.

**Comment by jxs** [comment] 2022-01-05 22:02
of course! Feel free to give it a try, if you need any help just ask :)

**Comment by yongwoon** [comment] 2022-01-06 05:11
@jxs 

Yes. almost same. Also  want to specify schema of `refinery_schema_history` table.
 
If already can specify schema, please tell me :)

**Comment by TobiasDeBruijn** [comment] 2022-01-06 11:01
Id be more than happy to try and implement that too. Though I'm not sure what the best approach would be. Do we require some columns to be present, and if not, how should we deal with that?

**Comment by jxs** [comment] 2022-01-06 12:43
addressed with https://github.com/rust-db/refinery/pull/207

**Closed by jxs** 2022-01-06 12:43 UTC

**Comment by rmagatti** [comment] 2024-01-25 18:08
Hey, I know it's been a while, but I'm not sure I see how the schema can be specified still?
Yes we can change the table name with `--table-name`, but can I pass `"schema_name"."table_name"` to the CLI as well for it to use the table under a specific given schema in the same database?

**Comment by jxs** [comment] 2024-02-13 20:50
Hi, that feature was added on #207 and it's exposed via [`Runner`](https://github.com/rust-db/refinery/pull/207/files#diff-8567c2a9cebe732417b29312c67683d2950208b05322ad5b78ac08be9c271f58R344-R365) but not yet via CLI I am afraid, would you like to take a stab and implement it?
