### ISSUE TITLE
Feature request: r2d2_sqlite connection pooling support

### ISSUE THREAD

**Issue by sbrl** [rust-db/refinery#79] opened 2020-03-31 22:40 UTC
Does _refinery_ have an option to support r2d2_sqlite for connection pooling?

The specific error I'm getting is as follows:

```
]error[E0277]: the trait bound `&mut r2d2::PooledConnection<r2d2_sqlite::SqliteConnectionManager>: refinery_migrations::traits::sync::Query<std::vec::Vec<refinery_migrations::AppliedMigration>>` is not satisfied
  --> wopplebloxd/src/db/migrations.rs:23:44
   |
23 |         embedded::migrations::runner().run(&mut connection);
   |                                            ^^^^^^^^^^^^^^^ the trait `refinery_migrations::traits::sync::Query<std::vec::Vec<refinery_migrations::AppliedMigration>>` is not implemented for `&mut r2d2::PooledConnection<r2d2_sqlite::SqliteConnectionManager>`
   |
   = note: required because of the requirements on the impl of `refinery::Migrate` for `&mut r2d2::PooledConnection<r2d2_sqlite::SqliteConnectionManager>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `wopplebloxd`.

To learn more, run the command again with --verbose.
```

I'm having to use connection pooling here because I'm setting up a web server with actix, and I'm storing my db connection in my global state object, which is access by multiple threads I assume that actix is spawning.

**Comment by jxs** [comment] 2020-06-03 12:53
hi, sorry for the late reply, as I only got to check connection pools while looking into #105. 
But doesn't [`with_init`](https://docs.rs/r2d2_sqlite/0.16.0/r2d2_sqlite/struct.SqliteConnectionManager.html#method.with_init) solve the problem?

**Comment by jxs** [comment] 2020-07-01 11:09
i am going to close this for now

**Closed by jxs** 2020-07-01 11:09 UTC
Labels: enhancement

**Comment by kartikynwa** [comment] 2024-04-02 08:41
`with_init` is not ideal. But I have only just begun testing this so can't say for sure.

The issue is that you would want to apply refinery migrations only once when the pool is being created. `with_init` on the other hand will try to do this for each connection in the pool.

**Comment by kartikynwa** [comment] 2024-04-02 17:28
Turns out we can take a connection for r2d2's connection pool and use with `Runner::run(...)`. r2d2's PooledConnection implements `DerefMut<Target = OriginalConnection>`where OriginalConnection is whatever Connection struct PooledConnection is an abstraction over. So we can do something like for example for `r2d2` and `r2d2_rusqlite`:

```rust
    let pool = r2d2::Pool::builder()
        .max_size(8)
        .build(manager)
        .expect("Unable to initialize SQLite connection pool");

    let conn: &mut rusqlite::Connection = &mut pool.get().unwrap();
    refinery::embed_migrations!("./migrations");
    migrations::runner().run(conn).unwrap();
```
